<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Buy_Eat" nsURI="www.Buy_Eat.com" nsPrefix="BE">
  <eClassifiers xsi:type="ecore:EClass" name="Buy_Eat">
    <eStructuralFeatures xsi:type="ecore:EReference" name="buyer" upperBound="-1"
        eType="#//Buyer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Food" upperBound="-1" eType="#//Food"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eater" upperBound="-1"
        eType="#//Eater" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eater" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Buyer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eatenBy" upperBound="-1"
        eType="#//Food" eOpposite="#//Food/eats"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Buyer" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedBy" upperBound="-1"
        eType="#//Eater"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Food">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eats" eType="#//Eater"
        eOpposite="#//Eater/eatenBy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
